config/routes.rb
HackTx::Application.routes.draw do
  get "welcome/index"

    resources :senders
    root 'welcome#index'
    match '/signup', to: 'users#new', via: 'get'

end

app/models/sender.rb
class Sender < ActiveRecord::Base
end

app/controllers/senders_controller.rb
class SendersController < ApplicationController
  before_action :set_sender, only: [:show, :edit, :update, :destroy]

  # GET /senders
  # GET /senders.json
  def index
    @senders = Sender.all
  end

  # GET /senders/1
  # GET /senders/1.json
  def show
  end

  # GET /senders/new
  def new
    @sender = Sender.new
  end

  # GET /senders/1/edit
  def edit
  end

  # POST /senders
  # POST /senders.json
  def create
    @sender = Sender.new(sender_params)

    respond_to do |format|
      if @sender.save
        format.html { redirect_to @sender, notice: 'Sender was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sender }
      else
        format.html { render action: 'new' }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /senders/1
  # PATCH/PUT /senders/1.json
  def update
    respond_to do |format|
      if @sender.update(sender_params)
        format.html { redirect_to @sender, notice: 'Sender was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /senders/1
  # DELETE /senders/1.json
  def destroy
    @sender.destroy
    respond_to do |format|
      format.html { redirect_to senders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sender
      @sender = Sender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sender_params
      params.require(:sender).permit(:email, :password)
    end
end

app/helpers/senders_helper.rb
module SendersHelper
end

app/views/senders/_form.html.erb
<%= form_for(@sender) do |f| %>
  <% if @sender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sender.errors.count, "error") %> prohibited this sender from being saved:</h2>

      <ul>
      <% @sender.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/senders/edit.html.erb
<h1>Editing sender</h1>

<%= render 'form' %>

<%= link_to 'Show', @sender %> |
<%= link_to 'Back', senders_path %>

app/views/senders/index.html.erb
<h1>Listing senders</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @senders.each do |sender| %>
      <tr>
        <td><%= sender.email %></td>
        <td><%= sender.password %></td>
        <td><%= link_to 'Show', sender %></td>
        <td><%= link_to 'Edit', edit_sender_path(sender) %></td>
        <td><%= link_to 'Destroy', sender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sender', new_sender_path %>

app/views/senders/new.html.erb
<h1>New sender</h1>

<%= render 'form' %>

<%= link_to 'Back', senders_path %>

app/views/senders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @sender.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @sender.password %>
</p>

<%= link_to 'Edit', edit_sender_path(@sender) %> |
<%= link_to 'Back', senders_path %>